repos:
  - repo: local
    hooks:
      - id: format-md
        name: Format markdown
        types: [markdown]
        language: system
        entry: rumdl check --fix

      - id: format-nix
        name: Format nix
        types: [nix]
        language: system
        entry: alejandra

      - id: format-rust
        name: Format rust
        types: [rust]
        language: system
        entry: rustfmt
